### ISSUE TITLE
飞桨PaddlePaddle期望能够参与

### ISSUE THREAD

**Issue by jzhang533** [osslab-pku/OSSDevelopment#1]
周老师，您好

飞桨社区注意到了您的课程当中的这条招募信息：https://github.com/osslab-pku/OSSDevelopment/tree/main/recruitOSSproject

我们在开展飞桨社区的过程中，很期望能为您的课程提供供学生进行实践的具体任务。

目前，我们有如下的任务，可供您先参考：

- [【PFCC-Roadmap】总览](https://github.com/PaddlePaddle/Paddle/issues/42571)
- [【PFCC】call-for-contributions](https://github.com/PaddlePaddle/community/tree/master/pfcc/call-for-contributions)
- [【社区活动】飞桨社区活动总览-飞桨黑客松](https://github.com/PaddlePaddle/Paddle/issues/42410)
- [【PR is welcome】GitHub Issue](https://github.com/PaddlePaddle/Paddle/labels/PR%20is%20welcome)

您也可以参考我们的仓库:[community](https://github.com/PaddlePaddle/community)，来了解更多信息。

稍后我给您发封邮件联系您。

@jzhang533 @luotao1 from PaddlePaddle community.

**Comment by minghuizhou** [comment]
Message received. Thank you for you interest! Will let you know once we want you involved.
