### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by PING020903** [osslab-pku/OSSDevelopment#8]
这是干嘛用的，GitHub怎么给我推送这东西的😂

**Comment by minghuizhou** [comment]
不知道github为啥推给你。这是一门课程的课件等材料。

**Comment by PING020903** [comment]
> 不知道github为啥推给你。这是一门课程的课件等材料。

破案了，原来是以前我不知道什么时候star了😂
不过一次都没有看过😥
现在刚入职没几天，就感觉现在我很缺乏阅读产品项目的能力，代码风格跟实验性代码完全不一样😫
